apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: django-app
  resourceVersion: 0.0.1
  namespace: default
service_labels:
  stolon-postgres: "yes"
base: gravitational.io/k8s-aws:0.0.0+latest
dependencies:
  apps:
    - gravitational.io/stolon-app:0.0.0+latest
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
  servers:
    node:
      min_count: 1
      cpu:
        min_count: 2
      ram:
        min_total_mb: 2000
      labels:
        role: "node"
        stolon-keeper: "yes"
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
      mounts:
        - source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: django-app-install
        namespace: default
      spec:
        template:
          metadata:
            name: django-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: django-controller:latest
                command: ["/djctl", "install"]
                env:
                  - name: DB_NAME
                    value: "django"
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: django-app-uninstall
        namespace: default
      spec:
        template:
          metadata:
            name: django-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: django-controller:latest
                command: ["/djctl", "uninstall"]
                env:
                  - name: DB_NAME
                    value: "django"
