apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: django-app
  resourceVersion: 0.0.1
  namespace: default
service_labels:
  stolon-postgres: "yes"
base: gravitational.io/k8s-onprem:0.0.0+latest
dependencies:
  apps:
    - gravitational.io/stolon-app:0.0.0+latest
    - gravitational.io/pithos-app:0.0.0+latest
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
          - device: vdc
            mb: 6000
  servers:
    master:
      cpu:
        min_count: 1
      ram:
        min_total_mb: 2000
    node:
      cpu:
        min_count: 1
      min_count: 2
      description: "stolon server"
      labels:
        role: "node"
        stolon-keeper: "yes"
      ram:
        min_total_mb: 2000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
          fs_types: ["xfs", "btrfs"]
      mounts:
        - source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: django-app-install
      spec:
        template:
          metadata:
            name: django-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: django-bootstrap:latest
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: django-app-uninstall
      spec:
        template:
          metadata:
            name: django-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: django-uninstall:latest
